#!/bin/bash

page_size=3
page_number=1
page_path="/tmp/wallpaper-page-number"
filter_path="/tmp/wallpaper-filter"
filter=""

# create temp files
echo 1 > $page_path
echo "" > $filter_path

  # Find the image files and format them as a JSON array
images () {
  let selection=$page_size*$page_number
  wallpapers="$HOME/Pictures/wallpapers"

  find -L "$wallpapers" -type f \( \
      -iname "*.jpg" -o \
      -iname "*.jpeg" -o \
      -iname "*.png" -o \
      -iname "*.gif" -o \
      -iname "*.pnm" -o \
      -iname "*.tga" -o \
      -iname "*.tiff" -o \
      -iname "*.webp" -o \
      -iname "*.bmp" -o \
      -iname "*.farbfeld" \
  \) | 
  grep "$filter" | 
  head -n $selection | 
  tail -n $page_size | 
  jq -Rsc 'split("\n") | map(select(length > 0))'
}

images

while [[ true ]]; do
  sleep 0.2
  file_number=$(cat $page_path)
  if [[ $page_number -ne $file_number ]]; then
    page_number=$file_number
    images
  fi

  new_filter=$(cat $filter_path)
  echo "=$filter="
  echo "=$new_filter="
  if [[ $filter == $new_filter ]]; then
    filter=$new_filter
    # images
  fi
done
